### ISSUE TITLE
install from github fails on windows

### ISSUE THREAD

**Issue by cstubbsphd** [rstats-db/odbc#68]
### Issue Description and Expected Result
I was trying the following tutorial: https://rviews.rstudio.com/2017/05/17/databases-using-r/
I successfully installed the dev version of `dplyr` and `dbplyr`, but the installation of `odbc` failed.

### Reproducible Example
```r
devtools::install_github("rstats-db/odbc")

Downloading GitHub repo rstats-db/odbc@master
from URL https://api.github.com/repos/rstats-db/odbc/zipball/master
Installing odbc
"C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/CStubbs/AppData/Local/Temp/Rtmpqczuzu/devtools16602a4a7aa8/rstats-db-odbc-342dcd6"  \
  --library="C:/Program Files/R/R-3.4.0patched/library" --install-tests 

* installing *source* package 'odbc' ...
** libs

*** arch - i386
(cd cctz && \
make libcctz.a PREFIX="../" CC="c:/Rtools/mingw_32/bin/gcc " CXX="c:/Rtools/mingw_32/bin/g++  -std=gnu++11" AR="c:/Rtools/mingw_32/bin/ar" ARFLAGS=rv)
make[1]: Entering directory `/cygdrive/c/Users/CStubbs/AppData/Local/Temp/Rtmpqczuzu/devtools16602a4a7aa8/rstats-db-odbc-342dcd6/src-i386/cctz'
c:/Rtools/mingw_32/bin/g++  -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_format.o src/time_zone_format.cc
src/time_zone_format.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_if.o src/time_zone_if.cc
src/time_zone_if.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_impl.o src/time_zone_impl.cc
src/time_zone_impl.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_info.o src/time_zone_info.cc
src/time_zone_info.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_libc.o src/time_zone_libc.cc
src/time_zone_libc.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_lookup.o src/time_zone_lookup.cc
src/time_zone_lookup.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_posix.o src/time_zone_posix.cc
src/time_zone_posix.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_32/bin/ar rv libcctz.a time_zone_format.o time_zone_if.o time_zone_impl.o time_zone_info.o time_zone_libc.o time_zone_lookup.o time_zone_posix.o
a - time_zone_format.o
a - time_zone_if.o
a - time_zone_impl.o
a - time_zone_info.o
a - time_zone_libc.o
a - time_zone_lookup.o
a - time_zone_posix.o
C:\Rtools\mingw_32\bin\ar.exe: creating libcctz.a
make[1]: Leaving directory `/cygdrive/c/Users/CStubbs/AppData/Local/Temp/Rtmpqczuzu/devtools16602a4a7aa8/rstats-db-odbc-342dcd6/src-i386/cctz'
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0PA/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.0patched/library/Rcpp/include" -I"C:/Program Files/R/R-3.4.0patched/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I. -DNANODBC_USE_BOOST_CONVERT -Icctz/include -Inanodbc   -O2 -Wall  -mtune=core2 -c connection.cpp -o connection.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0PA/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.0patched/library/Rcpp/include" -I"C:/Program Files/R/R-3.4.0patched/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I. -DNANODBC_USE_BOOST_CONVERT -Icctz/include -Inanodbc   -O2 -Wall  -mtune=core2 -c nanodbc/nanodbc.cpp -o nanodbc.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0PA/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.0patched/library/Rcpp/include" -I"C:/Program Files/R/R-3.4.0patched/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I. -DNANODBC_USE_BOOST_CONVERT -Icctz/include -Inanodbc   -O2 -Wall  -mtune=core2 -c result.cpp -o result.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0PA/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.0patched/library/Rcpp/include" -I"C:/Program Files/R/R-3.4.0patched/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I. -DNANODBC_USE_BOOST_CONVERT -Icctz/include -Inanodbc   -O2 -Wall  -mtune=core2 -c odbc_connection.cpp -o odbc_connection.o
In file included from C:/PROGRA~1/R/R-34~1.0PA/include/R.h:91:0,
                 from C:/Program Files/R/R-3.4.0patched/library/Rcpp/include/Rcpp/r/headers.h:52,
                 from C:/Program Files/R/R-3.4.0patched/library/Rcpp/include/RcppCommon.h:29,
                 from C:/Program Files/R/R-3.4.0patched/library/Rcpp/include/Rcpp.h:27,
                 from odbc_connection.h:6,
                 from odbc_connection.cpp:1:
C:/PROGRA~1/R/R-34~1.0PA/include/R_ext/RS.h:55:0: warning: "ERROR" redefined
 #define ERROR   ),error(R_problem_buf);}
 ^
In file included from C:/Rtools/mingw_32/i686-w64-mingw32/include/windows.h:71:0,
                 from sql_types.h:6,
                 from odbc_connection.h:4,
                 from odbc_connection.cpp:1:
C:/Rtools/mingw_32/i686-w64-mingw32/include/wingdi.h:75:0: note: this is the location of the previous definition
 #define ERROR 0
 ^
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0PA/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.0patched/library/Rcpp/include" -I"C:/Program Files/R/R-3.4.0patched/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I. -DNANODBC_USE_BOOST_CONVERT -Icctz/include -Inanodbc   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp: In function 'void R_init_odbc(DllInfo*)':
RcppExports.cpp:306:35: error: invalid conversion from 'int' to 'Rboolean' [-fpermissive]
     R_useDynamicSymbols(dll, FALSE);
                                   ^
In file included from C:/PROGRA~1/R/R-34~1.0PA/include/Rinternals.h:51:0,
                 from C:/Program Files/R/R-3.4.0patched/library/Rcpp/include/Rcpp/r/headers.h:53,
                 from C:/Program Files/R/R-3.4.0patched/library/Rcpp/include/RcppCommon.h:29,
                 from C:/Program Files/R/R-3.4.0patched/library/Rcpp/include/Rcpp.h:27,
                 from odbc_types.h:4,
                 from RcppExports.cpp:4:
C:/PROGRA~1/R/R-34~1.0PA/include/R_ext/Rdynload.h:84:10: note: initializing argument 2 of 'Rboolean R_useDynamicSymbols(DllInfo*, Rboolean)'
 Rboolean R_useDynamicSymbols(DllInfo *info, Rboolean value);
          ^
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.0PA/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.0PA/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="odbc.dll" ' had status 2
ERROR: compilation failed for package 'odbc'
* removing 'C:/Program Files/R/R-3.4.0patched/library/odbc'
* restoring previous 'C:/Program Files/R/R-3.4.0patched/library/odbc'
Installation failed: Command failed (1)
```
<details>
<summary>Session Info</summary>
```r
devtools::session_info()
#> output

Session info ----------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.4.0 Patched (2017-06-02 r72765)
 system   x86_64, mingw32                            
 ui       RStudio (1.0.143)                          
 language (EN)                                       
 collate  English_United States.1252                 
 tz       Europe/London                             
 date     2017-06-07                                 

Packages --------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.0   2017-06-06 local         
 compiler    3.4.0   2017-06-06 local         
 curl        2.6     2017-04-27 CRAN (R 3.4.0)
 datasets  * 3.4.0   2017-06-06 local         
 devtools    1.13.2  2017-06-02 CRAN (R 3.4.0)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
 git2r       0.18.0  2017-01-01 CRAN (R 3.4.0)
 graphics  * 3.4.0   2017-06-06 local         
 grDevices * 3.4.0   2017-06-06 local         
 httr        1.2.1   2016-07-03 CRAN (R 3.4.0)
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)
 methods   * 3.4.0   2017-06-06 local         
 R6          2.2.1   2017-05-10 CRAN (R 3.4.0)
 stats     * 3.4.0   2017-06-06 local         
 tools       3.4.0   2017-06-06 local         
 utils     * 3.4.0   2017-06-06 local         
 withr       1.0.2   2016-06-20 CRAN (R 3.4.0)
```
</details>

**Comment by jimhester** [comment]
This should now be fixed, thank you for the detailed error message!

**Comment by cstubbsphd** [comment]
Yes, it works now.  Thanks!

**Comment by NikkiPDX15** [comment]
How was this fixed??

**Comment by jimhester** [comment]
The two commits that fixed it are linked above, https://github.com/jimhester/odbc/commit/f9ad5ba370acf91aae06721c63f210e368532d28, https://github.com/rstats-db/odbc/commit/7eabaafdf09ce58b0e2e457affa98e950b9e43f7

**Comment by embubiz** [comment]
Hi.
I still can't instll the package.

Here is my error message:

`> devtools::install_github("rstats-db/odbc")
Downloading GitHub repo rstats-db/odbc@master
from URL https://api.github.com/repos/rstats-db/odbc/zipball/master
Installing odbc
"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/emiliano.bozzi/AppData/Local/Temp/RtmpG6egEs/devtools226c2f0d3770/rstats-db-odbc-5acc553"  \
  --library="C:/Users/emiliano.bozzi/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'odbc' ...
** libs
(cd cctz && \
/usr/bin/make libcctz.a PREFIX="../" CC="c:/Rtools/mingw_64/bin/gcc -m64" CXX="c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11" AR="c:/Rtools/mingw_64/bin/ar" ARFLAGS=rv)
make[1]: Entering directory `/cygdrive/c/Users/emiliano.bozzi/AppData/Local/Temp/RtmpG6egEs/devtools226c2f0d3770/rstats-db-odbc-5acc553/src/cctz'
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_format.o src/time_zone_format.cc
src/time_zone_format.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_if.o src/time_zone_if.cc
src/time_zone_if.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_impl.o src/time_zone_impl.cc
src/time_zone_impl.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_info.o src/time_zone_info.cc
src/time_zone_info.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_libc.o src/time_zone_libc.cc
src/time_zone_libc.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_lookup.o src/time_zone_lookup.cc
src/time_zone_lookup.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_posix.o src/time_zone_posix.cc
src/time_zone_posix.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/ar rv libcctz.a time_zone_format.o time_zone_if.o time_zone_impl.o time_zone_info.o time_zone_libc.o time_zone_lookup.o time_zone_posix.o
a - time_zone_format.o
a - time_zone_if.o
a - time_zone_impl.o
a - time_zone_info.o
a - time_zone_libc.o
a - time_zone_lookup.o
a - time_zone_posix.o
C:\Rtools\mingw_64\bin\ar.exe: creating libcctz.a
make[1]: Leaving directory `/cygdrive/c/Users/emiliano.bozzi/AppData/Local/Temp/RtmpG6egEs/devtools226c2f0d3770/rstats-db-odbc-5acc553/src/cctz'
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.0/include" -DNDEBUG  -I"C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/BH/include"   -I"C:/swarm/workspace/External-R-3.3.3/vendor/extsoft/include"  -I. -DNANODBC_USE_BOOST_CONVERT -Icctz/include -Inanodbc   -O2 -Wall  -mtune=core2 -c odbc_result.cpp -o odbc_result.o
In file included from odbc_result.cpp:1:0:
odbc_result.h: In constructor 'odbc::odbc_error::odbc_error(nanodbc::database_error, const string&)':
odbc_result.h:22:34: error: no matching function for call to 'Rcpp::exception::exception(const char [1], bool)'
       : Rcpp::exception("", false) {
                                  ^
odbc_result.h:22:34: note: candidates are:
In file included from C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/RcppCommon.h:122:0,
                 from C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp.h:27,
                 from odbc_result.h:3,
                 from odbc_result.cpp:1:
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:34:9: note: Rcpp::exception::exception(const char*, const char*, int)
         exception(const char* message_, const char* file, int line) : message(message_) {
         ^
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:34:9: note:   candidate expects 3 arguments, 2 provided
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:31:18: note: Rcpp::exception::exception(const char*)
         explicit exception(const char* message_) : message(message_) { // #nocov start
                  ^
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:31:18: note:   candidate expects 1 argument, 2 provided
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:29:11: note: Rcpp::exception::exception(const Rcpp::exception&)
     class exception : public std::exception {
           ^
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:29:11: note:   candidate expects 1 argument, 2 provided
make: *** [odbc_result.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.0/etc/x64/Makeconf" -f "C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.0/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="odbc.dll" WIN=64 TCLBIN=64 ' had status 2
ERROR: compilation failed for package 'odbc'
* removing 'C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/odbc'
* restoring previous 'C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/odbc'
Error: Command failed (1)`

I don't know, since this issue is closed, if I need to open a new one. I just thought the topic was the same.

Here is my session info:

`> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252
[4] LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] httr_1.2.1       compiler_3.4.0   R6_2.2.0         RevoUtils_10.0.4 tools_3.4.0      withr_1.0.2     
 [7] curl_2.6         memoise_1.1.0    git2r_0.18.0     digest_0.6.12    devtools_1.12.0 `

Thanks in advance!

EB

**Comment by jimhester** [comment]
Please open a new issue in the future. Your issue looks like you need to
update Rcpp to a later version.

**Comment by embubiz** [comment]
Hi.
I still can't install the package.

Here is my error message:

```
> devtools::install_github("rstats-db/odbc")
Downloading GitHub repo rstats-db/odbc@master
from URL https://api.github.com/repos/rstats-db/odbc/zipball/master
Installing odbc
"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/emiliano.bozzi/AppData/Local/Temp/RtmpG6egEs/devtools226c2f0d3770/rstats-db-odbc-5acc553"  \
  --library="C:/Users/emiliano.bozzi/Documents/R/win-library/3.4" --install-tests 
* installing *source* package 'odbc' ...
** libs
(cd cctz && \
/usr/bin/make libcctz.a PREFIX="../" CC="c:/Rtools/mingw_64/bin/gcc -m64" CXX="c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11" AR="c:/Rtools/mingw_64/bin/ar" ARFLAGS=rv)
make[1]: Entering directory `/cygdrive/c/Users/emiliano.bozzi/AppData/Local/Temp/RtmpG6egEs/devtools226c2f0d3770/rstats-db-odbc-5acc553/src/cctz'
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_format.o src/time_zone_format.cc
src/time_zone_format.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_if.o src/time_zone_if.cc
src/time_zone_if.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_impl.o src/time_zone_impl.cc
src/time_zone_impl.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_info.o src/time_zone_info.cc
src/time_zone_info.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_libc.o src/time_zone_libc.cc
src/time_zone_libc.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_lookup.o src/time_zone_lookup.cc
src/time_zone_lookup.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_posix.o src/time_zone_posix.cc
src/time_zone_posix.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2016 Google Inc. All Rights Reserved.
 ^
c:/Rtools/mingw_64/bin/ar rv libcctz.a time_zone_format.o time_zone_if.o time_zone_impl.o time_zone_info.o time_zone_libc.o time_zone_lookup.o time_zone_posix.o
a - time_zone_format.o
a - time_zone_if.o
a - time_zone_impl.o
a - time_zone_info.o
a - time_zone_libc.o
a - time_zone_lookup.o
a - time_zone_posix.o
C:\Rtools\mingw_64\bin\ar.exe: creating libcctz.a
make[1]: Leaving directory `/cygdrive/c/Users/emiliano.bozzi/AppData/Local/Temp/RtmpG6egEs/devtools226c2f0d3770/rstats-db-odbc-5acc553/src/cctz'
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.0/include" -DNDEBUG  -I"C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/BH/include"   -I"C:/swarm/workspace/External-R-3.3.3/vendor/extsoft/include"  -I. -DNANODBC_USE_BOOST_CONVERT -Icctz/include -Inanodbc   -O2 -Wall  -mtune=core2 -c odbc_result.cpp -o odbc_result.o
In file included from odbc_result.cpp:1:0:
odbc_result.h: In constructor 'odbc::odbc_error::odbc_error(nanodbc::database_error, const string&)':
odbc_result.h:22:34: error: no matching function for call to 'Rcpp::exception::exception(const char [1], bool)'
       : Rcpp::exception("", false) {
                                  ^
odbc_result.h:22:34: note: candidates are:
In file included from C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/RcppCommon.h:122:0,
                 from C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp.h:27,
                 from odbc_result.h:3,
                 from odbc_result.cpp:1:
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:34:9: note: Rcpp::exception::exception(const char*, const char*, int)
         exception(const char* message_, const char* file, int line) : message(message_) {
         ^
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:34:9: note:   candidate expects 3 arguments, 2 provided
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:31:18: note: Rcpp::exception::exception(const char*)
         explicit exception(const char* message_) : message(message_) { // #nocov start
                  ^
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:31:18: note:   candidate expects 1 argument, 2 provided
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:29:11: note: Rcpp::exception::exception(const Rcpp::exception&)
     class exception : public std::exception {
           ^
C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/Rcpp/include/Rcpp/exceptions.h:29:11: note:   candidate expects 1 argument, 2 provided
make: *** [odbc_result.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.0/etc/x64/Makeconf" -f "C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.0/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="odbc.dll" WIN=64 TCLBIN=64 ' had status 2
ERROR: compilation failed for package 'odbc'
* removing 'C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/odbc'
* restoring previous 'C:/Users/emiliano.bozzi/Documents/R/win-library/3.4/odbc'
Error: Command failed (1)
```

I don't know, since this issue is closed, if I need to open a new one. I just thought the topic was the same.

Here is my session info:

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252
[4] LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] httr_1.2.1       compiler_3.4.0   R6_2.2.0         RevoUtils_10.0.4 tools_3.4.0      withr_1.0.2     
 [7] curl_2.6         memoise_1.1.0    git2r_0.18.0     digest_0.6.12    devtools_1.12.0 
```

Thanks in advance!

EB

**Comment by diia813** [comment]
I want to let you know that this thread helped me out, I had to build about 8 packages from source to get it to work but this comment pointed me to the answer I needed.

jimhester > _'Your issue looks like you need to update Rcpp to a later version.'_

I am able to use all my database servers now in R!
